#!/bin/sh

# What we output to the current directory
output_json='peach-backup-data.json'
output_html='peach-backup.html'
img_base_dir='peach-backup-images'

# The HTML template (in this directory)
pug_template="$(dirname "$0")/peach-backup.pug"

if test -e "$output_json"; then
    echo "Moving old $output_json to $output_json.old"
    mv "$output_json" "$output_json.old"
fi

# Fetch something to log in if necessary
if ! peach /activity/isUnread -o /dev/null; then
    echo "Can't connect to Peach"
    exit 1
fi

# Save the current value of pagination so we can turn it back off if desired.
orig_pagination="$(peach /stream/allow-pagination | jq '.data.allowPagination')"

if test "$orig_pagination" = 'false'; then
    echo "Turning on pagination..."
    peach /stream/allow-pagination -d '{"allowPagination": true}' | jq -c
    sleep 8
fi

page_temp="$(mktemp -t peach-page-tmp.XXXXXX)"
full_temp="$(mktemp -t peach-full-tmp.XXXXXX)"
cleanup() { rm -f -- "$page_temp" "$full_temp"; }
trap 'exit $?' HUP INT QUIT TERM; trap cleanup exit

my_id="$(jq -r '.data.streams[0].id' "$HOME/.peach-session")"
until test "$cursor" = '0' -o "$cursor" = 'null'; do
    echo "Fetching page from stream $my_id${cursor:+ with cursor $cursor}..."
    peach "/stream/id/$my_id${cursor:+?cursor=$cursor}" > "$page_temp"
    sleep 4
    if test "$(jq -r '.success' "$page_temp")" = '0'; then
        echo "Failed! Bailing."
        break
    fi
    cursor="$(jq -r .data.cursor < "$page_temp")"

    jq --argjson types '{"image": ["src"], "gif": ["src"], "video": ["src", "posterSrc"]}' \
        -r '.data.posts[] | .id as $id | .message[] | . as $m | $types[.type] // empty | .[] | "\($id) \($m[.])"' "$page_temp" \
    | while read post_id img_url; do
        img_dir="$img_base_dir/$post_id"
        mkdir -p "$img_dir"
        img_file="$img_dir/$(basename "$img_url")"
        if ! test -e "$img_file"; then
            echo "Downloading image $img_file..."
            curl -s -o "$img_file" "$img_url"
            sleep 2
        fi
    done

    if test -s "$output_json"; then
        cp "$output_json" "$full_temp"
        jq --slurpfile newPage "$page_temp" '.posts = ($newPage[0].data.posts + .posts)' "$full_temp" > "$output_json"
    else
        jq --arg backupImageDir "$img_base_dir" '.data | .backupImageDir = $backupImageDir' "$page_temp" > "$output_json"
    fi

    # TODO: handle GNU date on Linux
    page_date="$(date -j -f '%s' $(jq -r '.data.posts[0].createdTime' "$page_temp"))"
    echo "Loaded entries back to $page_date; writing HTML to $output_html"
    pug --pretty --obj "$output_json" < "$pug_template" > "$output_html"
done

if test "$orig_pagination" = 'false'; then
    echo "Turning pagination back off..."
    peach /stream/allow-pagination -d '{"allowPagination": false}' | jq -c
fi

echo "Finished creating backup!"
